apiVersion: core.spinkube.dev/v1alpha1
kind: SpinApp
metadata:
  name: redis-spinapp
spec:
  image: "ghcr.io/spinkube/spin-operator/redis-sample:20240820-095510-g8d6b442"
  replicas: 1
  executor: containerd-shim-spin
# Steps to run this found at https://github.com/spinkube/spin-operator/pull/131